---
name: dl4tb
device: hpu
arch:
  type: Model
dataloader:
  type: DataLoader
  data_dir: data/images/
  batch_size: 64
  shuffle: true
  validation_split: 0.2
  num_workers: 4
optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0
  amsgrad: true
loss: cross_entropy
metrics:
- accuracy
- top_k_acc
lr_scheduler:
  type: StepLR
  step_size: 50
  gamma: 0.1
trainer:
  epochs: 25
  save_dir: saved/
  save_period: 1
  verbosity: 2
  monitor: 
  - min 
  - val_loss
  early_stop: 10
  tensorboard: true
  wandb: true