model:
  num_classes: 2
  lr: 0.001

processing:
  data_url: https://drive.google.com/uc?id=1KdpV3M27kV-_QOQOrAentfzZ2tew8YS-&
  batch_size: 64
  data_dir: data
  zip_file: tb_data.zip
  exports_dir: saved/exports

training:
  max_epochs: 10
  log_every_n_steps: 10
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  save_dir: saved
  deterministic: True
  device: hpu
  num_instances: 1
  bucket_cap_mb: 125

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  run:
    dir: saved/hydra
